name: Continuous Integration/ Continuous Deployment
on:
  pull_request_target:
    types:
      - closed
    branches: [dev]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: adding db creds
      run: sed -i 's|"postgres_host"|"${{secrets.DB_HOST}}"|g;s|"db_port"|"${{secrets.DB_PORT}}"|g;s|"database"|"${{secrets.DATABASE}}"|g;s|"qube_user"|"${{secrets.DB_USER}}"|g;s|"tibil@123"|"${{secrets.DB_PASSWORD}}"|g' config.ini
      shell: bash  
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: tibildocker/generator_ms:dev

    - name: Docker pull image and deploy from hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.DEV_HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        PORT: '22'
        script: |
          docker login
          docker pull tibildocker/generator_ms
          docker stop cqube_v5_generator_app_1 || true
          docker rm cqube_v5_generator_app_1 || true
          docker rmi tibildocker/generator_ms:dev || true
          docker run -d --name cqube_v5_generator_app_1 -p 3003:3003 --network cqube_v5_cqube_net tibildocker/generator_ms:dev

